# Generated by Django 5.0.6 on 2024-06-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Электроэнергия', 'electricity'), ('Горячая вода', 'hot water'), ('Холодная вода', 'cold water'), ('Жировка', 'ent'), ('Газ', 'gas')], max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-payment_date',),
            },
        ),
    ]
