# Generated by Django 5.0.6 on 2024-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('indications', models.IntegerField(verbose_name='Показания')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Тариф')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Холодная вода',
                'verbose_name_plural': 'Холодная вода',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('indications', models.IntegerField(verbose_name='Показания')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Тариф')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Электроэнергия',
                'verbose_name_plural': 'Электроэнергия',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('indications', models.DecimalField(decimal_places=3, max_digits=9, max_length=120, verbose_name='Показания')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Газ',
                'verbose_name_plural': 'Газ',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='HotWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('indications', models.IntegerField(verbose_name='Показания')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Тариф')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Горячая вода',
                'verbose_name_plural': 'Горячая вода',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Квартплата',
                'verbose_name_plural': 'Квартплата',
                'ordering': ('-payment_date',),
            },
        ),
    ]
