# Generated by Django 5.0.6 on 2024-06-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_coldwater_electricity_gas_hotwater_rent_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='indications',
            field=models.IntegerField(verbose_name='Показания'),
        ),
    ]
