# Generated by Django 5.0.6 on 2024-05-28 20:04

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=200, verbose_name='Валюта')),
                ('date_start', models.DateField(blank=True, default=django.db.models.functions.datetime.Now(), null=True, verbose_name='Дата создания')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
            ],
        ),
    ]
