# Generated by Django 5.0.6 on 2024-05-28 20:05

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date_start',
            field=models.DateField(blank=True, default=django.db.models.functions.datetime.Now, null=True, verbose_name='Дата создания'),
        ),
    ]
