# Generated by Django 5.0.6 on 2024-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0003_alter_debt_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date_start',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
