# Generated by Django 5.0.6 on 2024-05-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0006_alter_debt_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('Martial Arts', [('judo', 'Judo'), ('karate', 'Karate')]), ('Racket', [('badminton', 'Badminton'), ('tennis', 'Tennis')]), ('unknown', 'Unknown')], max_length=200, verbose_name='Валюта'),
        ),
    ]
