# Generated by Django 5.0.6 on 2024-05-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0007_alter_debt_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('solvency', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Платежеспособность')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Курс')),
                ('date', models.DateField(verbose_name='Дата')),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('byn', 'BYN'), ('rub', 'RUB')], max_length=200, verbose_name='Валюта')),
            ],
        ),
        migrations.AlterField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('byn', 'BYN'), ('rub', 'RUB')], max_length=200, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='debt',
            name='debtors',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='debt_manager.debtors', verbose_name='Должник'),
            preserve_default=False,
        ),
    ]
