# Generated by Django 5.0.6 on 2024-05-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0008_debtors_exchangerates_alter_debt_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debtors',
            new_name='Debtor',
        ),
        migrations.RenameModel(
            old_name='ExchangeRates',
            new_name='ExchangeRate',
        ),
    ]
