# Generated by Django 5.0.6 on 2024-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0010_alter_debt_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['date_end'], 'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.AlterModelOptions(
            name='debtor',
            options={'ordering': ['last_name'], 'verbose_name': 'Должник', 'verbose_name_plural': 'Должники'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['date'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='debt',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
    ]
