# Generated by Django 5.0.6 on 2024-06-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0013_debt_is_hidden_alter_debt_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='date_start',
        ),
        migrations.AddField(
            model_name='debt',
            name='date_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='debt',
            name='date_start_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
