# Generated by Django 5.0.6 on 2024-06-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0014_remove_debt_date_start_debt_date_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date_start_time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Время создания'),
        ),
    ]
