# Generated by Django 5.0.6 on 2024-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager', '0015_alter_debt_date_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время создания'),
        ),
    ]
